### ISSUE TITLE
2.0 images

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-solr#1]
Create 2.0 versions of images based on the [official Solr images](https://hub.docker.com/_/solr/) on Docker Hub.

Requirements:
- Use the official Solr images from Docker Hub. Supported versions are 5.x, 6.x and 7.x
- Make config overrides possible via the `project_root mount` in `/var/www/.docksal/etc/solr`
- Add automated tests
- Build and release via Travis CI

**Comment by christophersmith262** [comment]
Hi @lmakarov,

Our team has a need to use Solr 6.1 within our docksal environment and I would like to take a crack at getting this working if you don't mind.

Could you just clarify a few things:
* I'm assuming you're talking about this docker image as the starting point: https://hub.docker.com/_/solr/
* I'm assuming the default config files from search_api 8.x are what we want to provide by default?
* Can you elaborate on what automated testing might look like / what level of coverage is acceptable?
* Can you tell me more about what a travis release might look like? I'm not seeing an existing .travis.yml here.  Would the build be a part of this project or the main docksal project?

**Comment by lmakarov** [comment]
Hi @christophersmith262 !

> I'm assuming you're talking about this docker image as the starting point: https://hub.docker.com/_/solr/

Yes

> I'm assuming the default config files from search_api 8.x are what we want to provide by default?

Yes

> Can you elaborate on what automated testing might look like / what level of coverage is acceptable?

Confirming solr is up and is of the right version should be enough to start with.

> Can you tell me more about what a travis release might look like? I'm not seeing an existing .travis.yml here. Would the build be a part of this project or the main docksal project?

This repo does not have the Travis CI integration yet. See [docksal/service-cli](https://github.com/docksal/service-cli) for an example of a working one with automated tests (using `bats`) and releases to Docker Hub via Travis.

Feel free to reach out for support here or in [Gitter](https://gitter.im/lmakarov) if you have questions.

**Comment by lmakarov** [comment]
@christophersmith262 Just checking in to see if your team made any progress on this and if you are still interested to contribute here.

**Comment by Nebel54** [comment]
Hello there!

just as a quick heads up we are interested in contributing here and start working on it today.

**Comment by Nebel54** [comment]
Oh, there is already a PR: #2  - I will have a look at that one then.
