### ISSUE TITLE
Add 8.1 (stable) version

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-solr#10]
Add 8.1 (stable) version

http://lucene.apache.org/solr/community.html

> Version | Description
> 8.x | Current major version for feature releases (STABLE)
> 7.7.x | Version in the previous major release for bugfixes only (LTS)
> 9.0 | Next major version, yet to be released (UNSTABLE)
> <7.7 | All older versions are End Of Life (EOL)

Update the support matrix for Drupal in README

https://www.drupal.org/project/search_api_solr

This has to wait until 8.x Solr is supported in a stable release of search_api_solr

**Comment by waako** [comment]
Thanks for this, search_api_solr stable recommended release is now 3.0, which supports Solr 8.x

**Comment by mgurjanov** [comment]
Hello. Thanks for supporting this. But I can't seem to setup SOLR 8.1 with Drupal. I've read a lot and tried myself, but I am still new to Docksal and I could use some help. My docksal.yml file has this entry on SOLR:

`services:
  solr:
    hostname: solr
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/a:/opt/solr/server/solr/a:ro
      - ${PROJECT_ROOT}/../data/a/solr:/var/solr/a/data:rw
      - ${PROJECT_ROOT}/.docksal/etc/solr/a/conf:/var/lib/solr/a/conf:ro      
    image: solr:8.1
    labels:
      - io.docksal.virtual-host=solr.${VIRTUAL_HOST},solr.${VIRTUAL_HOST}.*
      - io.docksal.virtual-port=8983
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}`

And I have added this to my docksal.env file:

`SOLR_DEFAULT_CONFIG_SET=search_api_solr_8.x-3.0`

Solr container is started well but with 0 cores. I have also placed contents of solr_0.x_config.zip generated by Drupal, as I read that on this page [https://github.com/docksal/service-solr/tree/develop/configsets/search_api_solr_8.x-3.0/conf](url), but I still don't understand how to correctly create core for SOLR. solrcore.properties file generated by Drupal module only has this contents:

`solr.replication.confFiles=,stopwords_en.txt,synonyms_en.txt,protwords_en.txt,accents_en.txt,stopwords_und.txt,synonyms_und.txt,protwords_und.txt,accents_und.txt
solr.luceneMatchVersion=6.0`

And the one from template for 7.x has all this:

`solr.replication.master=false
solr.replication.slave=false
solr.replication.pollInterval=00:00:60
solr.replication.masterUrl=http://localhost:8983/solr
solr.replication.confFiles=schema.xml,elevate.xml
solr.mlt.timeAllowed=2000
solr.luceneMatchVersion=7.0
solr.selectSearchHandler.timeAllowed=-1
solr.autoCommit.MaxDocs=-1
solr.autoCommit.MaxTime=15000
solr.autoSoftCommit.MaxDocs=-1
solr.autoSoftCommit.MaxTime=-1
solr.install.dir=../../..`

Can someone please elaborate in more detail on required steps to make this work? Thank you.
