### ISSUE TITLE
Solr 8.1.1 and Drupal solr 3.0

### ISSUE THREAD

**Issue by b-connect** [docksal/service-solr#12]
```
Config set search_api_solr_8.x-3.0 not supported by Solr 8.1.1
```
Get this error.

**Comment by mokapost** [comment]
I'm running into this too. Set `SOLR_IMAGE` to `docksal/solr:8.1-edge` (currently the only 8.x container listed) and using the `Search API Solr 8.x-3.4` module. The `solr` container exits with the same error as OP immediately after project start.
