### ISSUE TITLE
Solr not restarting after a fin stop when using 6.6-2

### ISSUE THREAD

**Issue by ThomasJacobsWK** [docksal/service-solr#5]
We are currently using the solr 6.6-2 image + custom config in .docksal/etc/solr/conf/

The first time we start the project, everything is running ok. When we stop the project and restart it (fin stop / fin up), the solr is not coming online.

fin logs solr gives us this info:
> solr_1  | find: /opt/solr/server/solr/configsets/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned/user-owned: Symbolic link loop

**Comment by sergey-zabolotny** [comment]
Fixed in https://github.com/docksal/service-solr/pull/6
